### ISSUE TITLE
CiriQuant Python Version 2.7 Error

### ISSUE THREAD

**Issue by stefanerb89** [kendomaniac/docker4seq#5]
I got this error:

`
-1 SID16111_S6_L001_R1_001.fastq.gz -2 SID16111_S6_L001_R2_001.fastq.gz
Traceback (most recent call last):
  File "/home/serbe204/anaconda3/envs/CIRI/bin/CIRIquant", line 5, in <module>
    from CIRIquant.main import main
  File "/home/serbe204/anaconda3/envs/CIRI/lib/python2.7/site-packages/CIRIquant/main.py", line 191
    if args.no_fsj:
                  ^
IndentationError: unindent does not match any outer indentation level`
Any recommendations?

kind regards

**Comment by kendomaniac** [comment]
I redirect your question to the package developer
Cheers
Raf

From: stefanerb89 ***@***.***>
Date: Monday, 26 September 2022 at 11:09
To: kendomaniac/docker4seq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kendomaniac/docker4seq] CiriQuant Python Version 2.7 Error (Issue #5)

I got this error:

-1 SID16111_S6_L001_R1_001.fastq.gz -2 SID16111_S6_L001_R2_001.fastq.gz
Traceback (most recent call last):
File "/home/serbe204/anaconda3/envs/CIRI/bin/CIRIquant", line 5, in
from CIRIquant.main import main
File "/home/serbe204/anaconda3/envs/CIRI/lib/python2.7/site-packages/CIRIquant/main.py", line 191
if args.no_fsj:
^
IndentationError: unindent does not match any outer indentation level

Any recommendations?

kind regards

**Comment by giuferrero** [comment]
Hi stefanerb89,
Can you indicate to me the command that you used to run the analysis?
Best,
Giulio

**Comment by stefanerb89** [comment]
Hey Giulio,

 

I forget the command:

 

CIRIquant -t 20 -1 SID16111_S6_L001_R1_001.fastq.gz -2 SID16111_S6_L001_R2_001.fastq.gz --config /home/serbe204/Documents/config.yml -o /home/serbe204/Documents/KS_bulk -p SID16111 --no-fsj

 
Cheers

Gesendet: Montag, 26. September 2022 um 16:56 Uhr
Von: "giuferrero" ***@***.***>
An: "kendomaniac/docker4seq" ***@***.***>
Cc: "stefanerb89" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [kendomaniac/docker4seq] CiriQuant Python Version 2.7 Error (Issue #5)


 

Hi stefanerb89,
Can you indicate to me the command that you used to run the analysis?
Best,
Giulio

**Comment by stefanerb89** [comment]
Dear Giulio,

 

this is my log file. All paths in my config.yml are correct. Maybe it is a disc space error?

 

kind regards

Stephan

 

 

 

 
 

Gesendet: Montag, 26. September 2022 um 16:56 Uhr
Von: "giuferrero" ***@***.***>
An: "kendomaniac/docker4seq" ***@***.***>
Cc: "stefanerb89" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [kendomaniac/docker4seq] CiriQuant Python Version 2.7 Error (Issue #5)


 

Hi stefanerb89,
Can you indicate to me the command that you used to run the analysis?
Best,
Giulio

**Comment by giuferrero** [comment]
Hi Stephan,
I believed that you were talking about our Docker4Seq functions for the circRNA analysis, but you are discussing about CIRCquant and we are not the authors of this tool.
Please refer to the right authors of this method by looking at their website:
https://github.com/bioinfo-biols/CIRIquant
Best regards,
Giulio Ferrero
